name: Fetch Google Sheets Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client pandas
    
    - name: Create service account credentials
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > service_account.json
      shell: bash
    
    - name: Fetch and convert data
      run: python scripts/fetch_sheets.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update index.html from Google Sheets" && git push) 